-- VelociCAT official rally team platform
create table if not exists public.team_profile (
 id bigint primary key generated by default as identity, name text not null default 'VelociCAT',
 tagline text, story text, hero_image text, logo_url text, location text, email text, phone text,
 instagram_url text, facebook_url text, youtube_url text, tiktok_url text, updated_at timestamptz not null default now()
);
create table if not exists public.drivers (
 id bigint primary key generated by default as identity, name text not null, slug text not null unique,
 number text, role text not null default 'Pilot', bio text, photo_url text, car_id bigint references public.rally_cars(id) on delete set null,
 championship text, season integer, social_url text, published boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.rally_results (
 id bigint primary key generated by default as identity, event_id bigint references public.rally_events(id) on delete set null,
 driver_id bigint references public.drivers(id) on delete set null, car_id bigint references public.rally_cars(id) on delete set null,
 season integer not null, category text, overall_position integer, category_position integer, status text not null default 'finished',
 time text, gap text, summary text, published boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.news_posts (
 id bigint primary key generated by default as identity, title text not null, slug text not null unique, excerpt text,
 content text, cover_image text, category text not null default 'Actualitat', published boolean not null default false,
 published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.gallery_items (
 id bigint primary key generated by default as identity, title text, image_url text not null, caption text,
 category text not null default 'Rally', event_id bigint references public.rally_events(id) on delete set null,
 season integer, published boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.sponsors (
 id bigint primary key generated by default as identity, name text not null, logo_url text, website_url text,
 tier text not null default 'Partner', description text, published boolean not null default true, sort_order integer not null default 0,
 created_at timestamptz not null default now()
);
create table if not exists public.live_updates (
 id bigint primary key generated by default as identity, event_id bigint references public.rally_events(id) on delete cascade,
 driver_id bigint references public.drivers(id) on delete set null, stage text, position integer, category_position integer,
 time text, gap text, message text, is_live boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.contact_messages (
 id bigint primary key generated by default as identity, name text not null, email text, phone text, subject text not null,
 message text not null, created_at timestamptz not null default now(), status text not null default 'new'
);

do $$
declare t text;
begin
 foreach t in array array['team_profile','drivers','rally_results','news_posts','gallery_items','sponsors','live_updates','contact_messages'] loop
   execute format('alter table public.%I enable row level security', t);
 end loop;
end $$;

drop policy if exists "public read team profile" on public.team_profile;
create policy "public read team profile" on public.team_profile for select to anon, authenticated using (true);
drop policy if exists "public read drivers" on public.drivers;
create policy "public read drivers" on public.drivers for select to anon, authenticated using (published = true or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "public read results" on public.rally_results;
create policy "public read results" on public.rally_results for select to anon, authenticated using (published = true or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "public read news" on public.news_posts;
create policy "public read news" on public.news_posts for select to anon, authenticated using (published = true or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "public read gallery" on public.gallery_items;
create policy "public read gallery" on public.gallery_items for select to anon, authenticated using (published = true or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "public read sponsors" on public.sponsors;
create policy "public read sponsors" on public.sponsors for select to anon, authenticated using (published = true or (select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "public read live" on public.live_updates;
create policy "public read live" on public.live_updates for select to anon, authenticated using (true);
drop policy if exists "public contact insert" on public.contact_messages;
create policy "public contact insert" on public.contact_messages for insert to anon, authenticated with check (true);
drop policy if exists "admin contact read" on public.contact_messages;
create policy "admin contact read" on public.contact_messages for select to authenticated using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists "admin contact update" on public.contact_messages;
create policy "admin contact update" on public.contact_messages for update to authenticated using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

do $$
declare t text;
begin
 foreach t in array array['team_profile','drivers','rally_results','news_posts','gallery_items','sponsors','live_updates'] loop
   execute format('drop policy if exists "admin manage %1$s" on public.%1$s', t);
   execute format('create policy "admin manage %1$s" on public.%1$s for all to authenticated using ((select auth.jwt() -> ''app_metadata'' ->> ''role'') = ''admin'') with check ((select auth.jwt() -> ''app_metadata'' ->> ''role'') = ''admin'')', t);
 end loop;
end $$;

grant select on public.team_profile,public.drivers,public.rally_results,public.news_posts,public.gallery_items,public.sponsors,public.live_updates to anon,authenticated;
grant insert on public.contact_messages to anon,authenticated;
grant select,update on public.contact_messages to authenticated;
grant select,insert,update,delete on public.team_profile,public.drivers,public.rally_results,public.news_posts,public.gallery_items,public.sponsors,public.live_updates to authenticated;

create index if not exists drivers_published_idx on public.drivers(published,season);
create index if not exists results_season_idx on public.rally_results(season,published);
create index if not exists news_date_idx on public.news_posts(published,published_at desc);
create index if not exists gallery_event_idx on public.gallery_items(event_id,published);
create index if not exists live_event_idx on public.live_updates(event_id,is_live,created_at desc);