"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../../utils/supabase";
type Row=Record<string,any>; const tabs=["profile","drivers","news","sponsors","results","gallery","live","contacts"] as const; type Tab=typeof tabs[number];
const tableOf=(t:Tab)=>t==="profile"?"team_profile":t==="drivers"?"drivers":t==="news"?"news_posts":t==="sponsors"?"sponsors":t==="results"?"rally_results":t==="gallery"?"gallery_items":t==="live"?"live_updates":"contact_messages";
const labels:{[K in Tab]:string}={profile:"Escuderia",drivers:"Pilots",news:"Notícies",sponsors:"Patrocinadors",results:"Resultats",gallery:"Galeria",live:"Live",contacts:"Contactes"};
export default function ContentAdmin(){const[ready,setReady]=useState(false),[admin,setAdmin]=useState(false),[tab,setTab]=useState<Tab>("profile"),[rows,setRows]=useState<Row[]>([]),[editing,setEditing]=useState<Row|null>(null),[message,setMessage]=useState("");
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setAdmin(data.session?.user?.app_metadata?.role==="admin");setReady(true)})},[]);
useEffect(()=>{if(admin)load()},[admin,tab]);
async function load(){let q=supabase.from(tableOf(tab)).select("*");if(tab==="news")q=q.order("created_at",{ascending:false});else if(tab==="profile")q=q.order("id").limit(1);else q=q.order("id",{ascending:false});const{data,error}=await q;if(error)setMessage(error.message);else setRows(data||[])}
async function remove(id:number){if(!confirm("Eliminar aquest element?"))return;const{error}=await supabase.from(tableOf(tab)).delete().eq("id",id);setMessage(error?.message||"Element eliminat");load()}
async function save(data:Row){const clean={...data};delete clean.id;delete clean.created_at;delete clean.updated_at;if(tab==="news"&&clean.published&&!clean.published_at)clean.published_at=new Date().toISOString();const result=editing?.id?await supabase.from(tableOf(tab)).update(clean).eq("id",editing.id):await supabase.from(tableOf(tab)).insert(clean);setMessage(result.error?.message||(editing?"Canvis guardats":"Element creat"));setEditing(null);load()}
if(!ready)return <div className="p-10 font-bold">Carregant...</div>;if(!admin)return <main className="mx-auto max-w-lg p-10 text-center"><h1 className="text-3xl font-black">Accés restringit</h1><a href="/admin" className="mt-5 inline-block rounded bg-gray-900 px-5 py-3 font-black text-white">Anar a l'admin</a></main>;
return <main className="min-h-screen bg-gray-100"><header className="sticky top-0 z-20 flex items-center justify-between bg-gray-950 px-5 py-4 text-white"><b className="text-xl italic">VELOCI<span className="text-yellow-400">CAT</span> CMS</b><a href="/admin" className="rounded bg-red-600 px-4 py-2 font-black">Admin principal</a></header><div className="mx-auto max-w-7xl p-5 md:p-8"><div className="flex flex-wrap gap-2">{tabs.map(t=><button key={t} onClick={()=>{setTab(t);setEditing(null);setMessage("")}} className={"rounded px-4 py-2 font-black uppercase "+(tab===t?"bg-yellow-400 text-red-700":"bg-white")}>{labels[t]}</button>)}</div>{message&&<p className="mt-4 rounded bg-green-100 p-3 font-bold">{message}</p>}<div className="mt-6 grid gap-8 lg:grid-cols-[1fr_1.2fr]"><Editor tab={tab} row={editing} onSave={save} onCancel={()=>setEditing(null)}/><div className="rounded-2xl bg-white p-6 shadow"><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-black uppercase">{labels[tab]}</h2>{tab!=="contacts"&&<button onClick={()=>setEditing({published:true,is_live:true,season:new Date().getFullYear(),name:tab==="profile"?"VelociCAT":""})} className="rounded bg-gray-950 px-4 py-2 font-black uppercase text-white">+ Nou</button>}</div><div className="space-y-3">{rows.map(r=><div key={r.id} className="rounded border p-4"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><Summary tab={tab} row={r}/></div>{tab!=="contacts"&&<div className="flex gap-2 shrink-0"><button onClick={()=>setEditing(r)} className="rounded bg-gray-100 px-3 py-2 font-bold">Editar</button><button onClick={()=>remove(r.id)} className="rounded bg-red-100 px-3 py-2 font-bold text-red-700">Eliminar</button></div>}</div>{tab==="contacts"&&<button onClick={async()=>{await supabase.from("contact_messages").update({status:r.status==="new"?"read":"new"}).eq("id",r.id);load()}} className="mt-3 rounded bg-gray-900 px-3 py-2 text-xs font-black uppercase text-white">{r.status==="new"?"Marcar llegit":"Marcar nou"}</button>}</div>)}</div></div></div></div></main>}
function Summary({tab,row}:{tab:Tab,row:Row}){if(tab==="profile")return <><b>{row.name}</b><p className="text-sm text-gray-500">{row.tagline||"Sense tagline"}</p></>;if(tab==="drivers")return <><b>{row.name} #{row.number||"—"}</b><p className="text-sm text-gray-500">{row.role} · {row.championship||"Sense campionat"}</p></>;if(tab==="news")return <><b>{row.title}</b><p className="text-sm text-gray-500">{row.category} · {row.published?"Publicada":"Esborrany"}</p></>;if(tab==="sponsors")return <><b>{row.name}</b><p className="text-sm text-gray-500">{row.tier} · {row.published?"Visible":"Ocult"}</p></>;if(tab==="results")return <><b>Temporada {row.season} · {row.category||"Classificació"}</b><p className="text-sm text-gray-500">{row.status} · P{row.category_position||row.overall_position||"—"}</p></>;if(tab==="gallery")return <><b>{row.title||"Foto"}</b><p className="text-sm text-gray-500">{row.category} · {row.published?"Visible":"Oculta"}</p></>;if(tab==="live")return <><b>{row.stage||"Actualització"}</b><p className="text-sm text-gray-500">{row.message||"Sense missatge"} · {row.is_live?"LIVE":"Arxivat"}</p></>;return <><b>{row.name} · {row.subject}</b><p className="text-sm text-gray-500">{row.email||row.phone||""} · {row.status}</p><p className="mt-2 whitespace-pre-wrap">{row.message}</p></>}
function Editor({tab,row,onSave,onCancel}:{tab:Tab,row:Row|null,onSave:(r:Row)=>void,onCancel:()=>void}){const[form,setForm]=useState<Row>(row||{});useEffect(()=>setForm(row||{}),[row]);if(tab==="contacts")return <div className="rounded-2xl bg-white p-6 shadow"><h2 className="text-2xl font-black uppercase">Contactes</h2><p className="mt-4 text-gray-500">Els contactes es gestionen des de la llista.</p></div>;
const fields:Record<Exclude<Tab,"contacts">,Array<[string,string,string]>>={profile:[["name","Nom","input"],["tagline","Tagline","input"],["story","Història","area"],["hero_image","Hero URL","input"],["logo_url","Logo URL","input"],["location","Ubicació","input"],["email","Email","input"],["phone","Telèfon","input"],["instagram_url","Instagram","input"],["facebook_url","Facebook","input"],["youtube_url","YouTube","input"],["tiktok_url","TikTok","input"]],drivers:[["name","Nom","input"],["slug","Slug","input"],["number","Dorsal","input"],["role","Rol","input"],["championship","Campionat","input"],["season","Temporada","number"],["photo_url","Foto URL","input"],["social_url","Xarxa social","input"],["bio","Biografia","area"]],news:[["title","Títol","input"],["slug","Slug","input"],["category","Categoria","input"],["cover_image","Portada URL","input"],["excerpt","Extracte","area"],["content","Contingut","area"]],sponsors:[["name","Nom","input"],["tier","Nivell","input"],["logo_url","Logo URL","input"],["website_url","Web","input"],["description","Descripció","area"],["sort_order","Ordre","number"]],results:[["season","Temporada","number"],["event_id","ID Rally","number"],["driver_id","ID Pilot","number"],["car_id","ID Vehicle","number"],["category","Categoria","input"],["overall_position","Posició absoluta","number"],["category_position","Posició categoria","number"],["status","Estat","input"],["time","Temps","input"],["gap","Gap","input"],["summary","Resum","area"]],gallery:[["title","Títol","input"],["image_url","Imatge URL","input"],["caption","Peu de foto","area"],["category","Categoria","input"],["event_id","ID Rally","number"],["season","Temporada","number"]],live:[["event_id","ID Rally","number"],["driver_id","ID Pilot","number"],["stage","Tram","input"],["position","Posició","number"],["category_position","Posició categoria","number"],["time","Temps","input"],["gap","Gap","input"],["message","Missatge","area"]]};
const numeric=new Set(["season","event_id","driver_id","car_id","overall_position","category_position","sort_order","position"]);
return <form onSubmit={e=>{e.preventDefault();const payload={...form};numeric.forEach(k=>{if(k in payload)payload[k]=payload[k]===""?null:Number(payload[k])});if(["drivers","news","sponsors","results","gallery","live"].includes(tab))payload.published=form.published!==false;if(tab==="live")payload.is_live=form.is_live!==false;onSave(payload)}} className="rounded-2xl bg-white p-6 shadow"><div className="flex items-center justify-between"><h2 className="text-2xl font-black uppercase">{row?"Editar":"Nou"}</h2>{row&&<button type="button" onClick={onCancel} className="font-bold text-gray-500">Tancar</button>}</div>{fields[tab].map(([name,label,type])=><label key={name} className="mt-4 block text-sm font-bold">{label}{type==="area"?<textarea value={form[name]??""} onChange={e=>setForm({...form,[name]:e.target.value})} rows={4} className="mt-1 w-full rounded border px-3 py-2"/>:<input type={type==="number"?"number":"text"} value={form[name]??""} onChange={e=>setForm({...form,[name]:e.target.value})} className="mt-1 w-full rounded border px-3 py-2"/>}</label>)}{tab!=="profile"&&<label className="mt-4 flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.published!==false} onChange={e=>setForm({...form,published:e.target.checked})}/> Publicat/visible</label>}{tab==="live"&&<label className="mt-4 flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.is_live!==false} onChange={e=>setForm({...form,is_live:e.target.checked})}/> En directe</label>}<button className="mt-6 w-full rounded bg-yellow-400 py-3 font-black uppercase text-red-700">Guardar</button></form>}
